### ISSUE TITLE
Privacy policy is out dated

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn.io#133]
__Describe the Bug__

Privacy policy on bpmn.io is outdated and needs fixing (Feedback Jil).

----

### Context

Scope of our project:

* bpmn.io
* forum.bpmn.io
* demo.bpmn.io

The DRI is Desktop Modeler/bpmn.io team / @nikku

### Web Marketing Involvement

We inherit general tracking strategies (and tools) set up by Camunda (Web Marketing):

  * Using Osano for consent management
  * Using Google Tag Manager for website tracking

If Camunda changes tracking strategies, we adopt

### Privacy Policy

Content owned by Camunda Legal.

-----

### Tasks

Agreed with Jil (2022-05-05):

* [ ] Do not host policy ourselves, but link to [Camunda Privacy Page](https://camunda.com/legal/privacy/)
    * [ ] bpmn.io
    * [ ] demo.bpmn.io
    * [ ] forum.bpmn.io
    * [ ] Put a redirect in place from original bpmn.io link
* [ ] Cross-check [Camunda Privacy Page](https://camunda.com/legal/privacy/) if it applies to our tools
